---
title: "test"
author: "Xinyi Lin"
date: "10/1/2019"
output: html_document
---

```{r}
library(ICSNP)
set.seed(123456)
X <- rmvnorm(20, c(0, 0, 0, 0), diag(1:4))
Y <- rmvnorm(30, c(0.5, 0.5, 0.5, 0.5), diag(1:4))
Z <- rbind(X, Y)
g <- factor(rep(c(1,2),c(20,30)))

HotellingsT2(X, Y)
HotellingsT2(Z ~ g, mu = rep(-0.5,4))
```

```{r}
library(Hotelling)
data(container.df)
fit = hotelling.test(.~gp, data = container.df)
fit

subs.df = container.df[1:10,]
subs.df$gp = rep(1:2, c(5,5))
fitPerm = hotelling.test(Al+Fe~gp, data  = subs.df, perm =  TRUE)
fitPerm
plot(fitPerm)

data(bottle.df)
fit12 = hotelling.test(.~Number, data = bottle.df)
fit12

fit23 = hotelling.test(.~Number, data = bottle.df, pair = c(2,3))
fit23
```

For a)

```{r}
library(Hotelling)
zerbe2 = read.table("./ZERBE2.DAT") %>% 
  select(-V2)
colnames(zerbe2) = c("group", "hour0", "hour0.5", "hour1", "hour1.5", "hour2", "hour3")
fita = hotelling.test(.~group, data = zerbe2)
fita
```

For b)

```{r}
zerbe2b = zerbe2 %>%
  mutate(diff1 = hour0.5-hour0, 
         diff2 = hour1-hour0.5, 
         diff3 = hour1.5-hour1, 
         diff4 = hour2-hour1.5, 
         diff5 = hour3-hour2) %>% 
  select(group, diff1:diff5)
fitb = hotelling.test(.~group, data = zerbe2b)
fitb
```